#!/usr/bin/env bash
# what keep your Ubuntu container’s Nginx installation from listening on port 8?
# configures nginx to run and to port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
